// All default scoring keywords, weights, and exclusions.
// These are used when no config file is provided, or as the base
// when a config file uses `extends: defaults`.

export const SCORING_DEFAULTS = {
  weights: {
    titleStrong: 50,
    titleModerate: 25,
    descriptionSignal: 3,
    highSignalBonus: 15,
    highSignalThreshold: 8,
    highSignalScoreCeiling: 25,
  },

  // Title keywords are strong signals — these mean the role IS a tech role
  titleStrong: [
    "software engineer",
    "software developer",
    "senior engineer",
    "staff engineer",
    "principal engineer",
    "tech lead",
    "engineering manager",
    "engineering director",
    "vp of engineering",
    "head of engineering",
    "full stack",
    "fullstack",
    "front end",
    "frontend",
    "back end",
    "backend",
    "devops",
    "sre",
    "site reliability",
    "platform engineer",
    "infrastructure engineer",
    "cloud engineer",
    "data engineer",
    "ml engineer",
    "machine learning engineer",
    "ai engineer",
    "product engineer",
    "web developer",
    "mobile developer",
    "ios developer",
    "android developer",
    "react developer",
    "node developer",
    "python developer",
  ],

  // Title keywords that are relevant but weaker (could be tech-adjacent)
  titleModerate: [
    "cto",
    "chief technology",
    "product manager",
    "technical project manager",
    "solutions architect",
    "solution architect",
    "systems architect",
    "technical lead",
    "technical director",
    "director of technology",
    "head of technology",
    "head of engineering",
    "director of engineering",
    "director of it",
    "it manager",
    "it director",
    "data scientist",
    "data analyst",
    "database administrator",
    "security engineer",
    "qa engineer",
    "test engineer",
  ],

  // Description keywords that indicate a tech role when found in quantity
  descriptionSignals: [
    "react", "typescript", "javascript", "python", "node.js", "nodejs",
    "aws", "gcp", "azure", "docker", "kubernetes", "terraform",
    "ci/cd", "git", "api", "rest", "graphql", "microservices",
    "agile", "scrum", "sprint", "pull request",
    "frontend", "backend", "full-stack", "fullstack",
    "postgresql", "mongodb", "redis", "sql",
    "machine learning", "deep learning", "llm", "ai model",
    "react native", "ios", "android", "mobile app",
    "html", "css", "sass", "webpack", "vite",
    "java", "go", "golang", "rust", "ruby", "rails",
    "django", "flask", "express", "next.js", "nextjs",
  ],

  // Titles that should be excluded — these aren't tech roles even if they mention tech
  exclusions: [
    "director of operations",
    "director of development",
    "director of communications",
    "director of finance",
    "director of people",
    "director of programs",
    "director of fundraising",
    "director of marketing",
    "director of hr",
    "director of human resources",
    "associate director",
    "assistant director",
    "executive director",
    "executive assistant",
    "development director",
    "development manager",
    "development associate",
    "development coordinator",
    "fundraising",
    "grant writer",
    "social worker",
    "case manager",
    "program manager",
    "program director",
    "program coordinator",
    "program officer",
    "policy director",
    "policy analyst",
    "policy manager",
    "communications director",
    "communications manager",
    "outreach coordinator",
    "community organizer",
    "volunteer coordinator",
    "help desk technician",
    "office manager",
    "administrative",
    "receptionist",
    "accountant",
    "bookkeeper",
    "controller",
    "legal counsel",
    "attorney",
    "paralegal",
    "nurse",
    "physician",
    "therapist",
    "counselor",
    "teacher",
    "instructor",
    "tutor",
    "forester",
    "gardener",
    "custodian",
    "janitor",
    "driver",
    "cook",
    "chef",
    "membership assistant",
    "carbon management",
    "artistic operations",
  ],
};

export const REMOTE_DEFAULTS = {
  terms: ["remote", "telecommute"],
};
